# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BukuTelefon.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(910, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnMenyimpan = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenyimpan.setGeometry(QtCore.QRect(560, 20, 211, 41))
        self.btnMenyimpan.setObjectName("btnMenyimpan")
        self.btnMenghapus = QtWidgets.QPushButton(self.centralwidget)
        self.btnMenghapus.setGeometry(QtCore.QRect(560, 70, 211, 41))
        self.btnMenghapus.setObjectName("btnMenghapus")
        self.btnMemperbarui = QtWidgets.QPushButton(self.centralwidget)
        self.btnMemperbarui.setGeometry(QtCore.QRect(560, 120, 211, 41))
        self.btnMemperbarui.setObjectName("btnMemperbarui")
        self.btnDaftar = QtWidgets.QPushButton(self.centralwidget)
        self.btnDaftar.setGeometry(QtCore.QRect(560, 170, 211, 41))
        self.btnDaftar.setObjectName("btnDaftar")
        self.txtID = QtWidgets.QLineEdit(self.centralwidget)
        self.txtID.setGeometry(QtCore.QRect(220, 20, 311, 41))
        self.txtID.setObjectName("txtID")
        self.txtNamaDepan = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNamaDepan.setGeometry(QtCore.QRect(220, 70, 311, 41))
        self.txtNamaDepan.setObjectName("txtNamaDepan")
        self.txtNamaBelakang = QtWidgets.QLineEdit(self.centralwidget)
        self.txtNamaBelakang.setGeometry(QtCore.QRect(220, 120, 311, 41))
        self.txtNamaBelakang.setObjectName("txtNamaBelakang")
        self.txtKota = QtWidgets.QLineEdit(self.centralwidget)
        self.txtKota.setGeometry(QtCore.QRect(220, 170, 311, 41))
        self.txtKota.setObjectName("txtKota")
        self.txtTelefon = QtWidgets.QLineEdit(self.centralwidget)
        self.txtTelefon.setGeometry(QtCore.QRect(220, 220, 311, 41))
        self.txtTelefon.setObjectName("txtTelefon")
        self.txtEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(220, 270, 311, 41))
        self.txtEmail.setObjectName("txtEmail")
        self.lblID = QtWidgets.QLabel(self.centralwidget)
        self.lblID.setGeometry(QtCore.QRect(10, 20, 201, 41))
        self.lblID.setObjectName("lblID")
        self.lblNamaDepan = QtWidgets.QLabel(self.centralwidget)
        self.lblNamaDepan.setGeometry(QtCore.QRect(10, 70, 201, 41))
        self.lblNamaDepan.setObjectName("lblNamaDepan")
        self.lblNamaBelakang = QtWidgets.QLabel(self.centralwidget)
        self.lblNamaBelakang.setGeometry(QtCore.QRect(10, 120, 201, 41))
        self.lblNamaBelakang.setObjectName("lblNamaBelakang")
        self.lblKota = QtWidgets.QLabel(self.centralwidget)
        self.lblKota.setGeometry(QtCore.QRect(10, 170, 201, 41))
        self.lblKota.setObjectName("lblKota")
        self.lblTelefon = QtWidgets.QLabel(self.centralwidget)
        self.lblTelefon.setGeometry(QtCore.QRect(10, 220, 201, 41))
        self.lblTelefon.setObjectName("lblTelefon")
        self.lblEmail = QtWidgets.QLabel(self.centralwidget)
        self.lblEmail.setGeometry(QtCore.QRect(10, 270, 201, 41))
        self.lblEmail.setObjectName("lblEmail")
        self.tblDaftar = QtWidgets.QTableWidget(self.centralwidget)
        self.tblDaftar.setGeometry(QtCore.QRect(10, 330, 891, 341))
        self.tblDaftar.setObjectName("tblDaftar")
        self.tblDaftar.setColumnCount(0)
        self.tblDaftar.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 910, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMenyimpan.setText(_translate("MainWindow", "Menyimpan"))
        self.btnMenghapus.setText(_translate("MainWindow", "Menghapus"))
        self.btnMemperbarui.setText(_translate("MainWindow", "Memperbarui"))
        self.btnDaftar.setText(_translate("MainWindow", "Daftar"))
        self.lblID.setText(_translate("MainWindow", "ID"))
        self.lblNamaDepan.setText(_translate("MainWindow", "Nama Depan"))
        self.lblNamaBelakang.setText(_translate("MainWindow", "Nama Belakang"))
        self.lblKota.setText(_translate("MainWindow", "Kota"))
        self.lblTelefon.setText(_translate("MainWindow", "Telefon"))
        self.lblEmail.setText(_translate("MainWindow", "Email"))
